---
- name: "Simple configuration"
  hosts: all
  connection: local
  gather_facts: no
  vars:
      conf_dir: "{{ playbook_dir }}/.compiled/"

  pre_tasks:
    - name: "Assign tmp folder to host"
      set_fact:
         host_tmpdir: "{{ conf_dir}}/{{ inventory_hostname}}"
      changed_when: no   # Don't report changes
      check_mode: no     # Always make changes
    - name: "Make sure there are no remains from a previous run"
      file:
        path: "{{ host_tmpdir }}"
        state: absent
      changed_when: no   # Don't report changes
      check_mode: no     # Always make changes
    - name: "Create folder to store configurations and diffs for/from the devices"
      file:
        path: "{{ host_tmpdir }}"
        state: directory
      changed_when: no   # Don't report changes
      check_mode: no     # Always make changes

- name: "Automated Configuration"
  hosts: all
  connection: local
  roles:
    - base
    - ip

  post_tasks:
    - name: "Assemble all the configuration bits"
      assemble:
          src: "{{ host_tmpdir }}/"
          dest: "{{ host_tmpdir }}/assembled.conf"
      changed_when: no   # Don't report changes
      check_mode: no     # Always make changes
    - name: "Load configuration into the device"
      napalm_install_config:
        hostname: "{{ host }}"
        username: "{{ user }}"
        dev_os: "{{ os }}"
        private_key_file: {{ key_file }}
        # password: "{{ password }}"
        config_file: "{{ host_tmpdir }}/assembled.conf"
        commit_changes: "{{ not ansible_check_mode }}"
        replace_config: false
        get_diffs: true
        diff_file: "{{ host_tmpdir }}/diff"
      tags: [print_action]
